-- db config based on the moodle example (db name swe1db instead of swe1user): 
-- docker command: docker run --name swe1db -e POSTGRES_USER=swe1user -e POSTGRES_PASSWORD=swe1pw -e POSTGRES_DB=swe1db -p 5432:5432 postgres

CREATE TABLE "cards" (
  "id" uuid PRIMARY KEY,
  "name" varchar,
  "damage" float,
  "deck" boolean,
  "trade" boolean,
  "username" varchar
);

CREATE TABLE "users" (
  "username" varchar PRIMARY KEY,
  "password" varchar,
  "coins" int,
  "name" varchar,
  "bio" varchar,
  "image" varchar
);

CREATE TABLE "packages" (
  "pid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card1" uuid,
  "card2" uuid,
  "card3" uuid,
  "card4" uuid,
  "card5" uuid
);

CREATE TABLE "stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wins" int,
  "losses" int,
  "elo" int,
  "username" varchar
);

CREATE TABLE "trade" (
  "tradeid" uuid PRIMARY KEY,
  "cardtotrade" uuid,
  "type" varchar,
  "mindmg" float
);

ALTER TABLE "cards" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "packages" ADD FOREIGN KEY ("card1") REFERENCES "cards" ("id");

ALTER TABLE "packages" ADD FOREIGN KEY ("card2") REFERENCES "cards" ("id");

ALTER TABLE "packages" ADD FOREIGN KEY ("card3") REFERENCES "cards" ("id");

ALTER TABLE "packages" ADD FOREIGN KEY ("card4") REFERENCES "cards" ("id");

ALTER TABLE "packages" ADD FOREIGN KEY ("card5") REFERENCES "cards" ("id");

ALTER TABLE "stats" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "trade" ADD FOREIGN KEY ("cardtotrade") REFERENCES "cards" ("id");
